



export const GET_USER_SUBSCRIPTION_REQUEST = "GET_USER_SUBSCRIPTION_REQUEST";
export const GET_USER_SUBSCRIPTION_SUCCESS = "GET_USER_SUBSCRIPTION_SUCCESS";
export const GET_USER_SUBSCRIPTION_FAILURE = "GET_USER_SUBSCRIPTION_FAILURE";

export const UPGRADE_USER_SUBSCRIPTION_REQUEST = "UPGRADE_USER_SUBSCRIPTION_REQUEST";
export const UPGRADE_USER_SUBSCRIPTION_SUCCESS = "UPGRADE_USER_SUBSCRIPTION_SUCCESS";
export const UPGRADE_USER_SUBSCRIPTION_FAILURE = "UPGRADE_USER_SUBSCRIPTION_FAILURE";

